[package]
name = "website"
version = "0.1.0"
authors = ["Abhinandh S <abhinandhsuby@proton.me>"]
edition = "2024"

[lib]
crate-type = ["cdylib"]

[features]

[dependencies]
# Use 0.12 for better compatibility with Axum 0.7
askama = { version = "0.12", features = ["with-axum"] } 
axum = { version = "0.7", default-features = false, features = ["macros"] }
axum-js-fetch = { git = "https://github.com/seanaye/axum-js-fetch" }
futures-lite = "2.3.0"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3.69", features = ["Request", "Response"] }


[dev-dependencies]
wasm-bindgen-test = "0.3.37"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "z"


