[package]
name = "abhinandhs_deno_dev"
version = "0.1.0"
edition = "2021"

[dependencies]
web-sys = "0.3.70"
yew = { version = "0.22.0", features = ["csr"] }
yew-router = "0.19.0"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true
