name: Deploy

on:
  push:
    branches: ["*"]
  pull_request:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: ðŸ“¦ Checkout repository
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: ðŸ¦€ Set up Rust and wasm32 target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Build step
        run: "deno task build"

      - name: Download Tailwind CSS CLI (v3)
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.17/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64

      - name: Build Tailwind CSS
        run: |
          ./tailwindcss-linux-x64 \
            -i ./assets/input.css \
            -o ./static/style.css \
            --minify

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Show repo structure
        run: |
          tree -L 4
          wc -l static/style.css
          cat static/style.css

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "abhinandhs"
          entrypoint: "run.ts"
          root: "."
